AWSTemplateFormatVersion: 2010-09-09
Resources:
  webAppBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
 
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref webAppBucket
                - /*
      Bucket: !Ref webAppBucket

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - webAppBucket
      - WebsiteURL
    Description: URL for website hosted on S3
